In [2]:
import numpy as np

#### 1. Create a 1D Numpy array with values from 0 to 9.


In [4]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 2. Create a Numpy array with values ranging from 10 to 49.

In [7]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 3.Create a 2D Numpy array and change the data type to float

In [39]:
a1= np.array([[1,2, 3],
           [4,5,6]])
a1.astype(float)

2

#### 4. Create a 4x4 identity matrix.

In [14]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#### 5. Create a Numpy array with 10 values evenly spaced between 1 and 5.

In [15]:
np.linspace(1,5,num=10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

#### 6. Create a 3x3 Numpy array with random values.

In [18]:
np.random.random((3,3))

array([[0.22515491, 0.22696883, 0.95869506],
       [0.10388975, 0.02204626, 0.34019879],
       [0.40924302, 0.15841719, 0.58862587]])

#### 7. Create a Numpy array with 20 random values and reshape it to a 4x5 array.

In [24]:
l1=np.random.random(20)
l1.reshape(4,5)

array([[0.18088804, 0.49013454, 0.24002253, 0.52395068, 0.2979853 ],
       [0.81810284, 0.24214934, 0.21773189, 0.64097155, 0.17683339],
       [0.94419655, 0.79518064, 0.82946634, 0.87117584, 0.16643643],
       [0.75168507, 0.70129844, 0.74681194, 0.00327697, 0.23495389]])

#### 8. Create an array of shape (3, 3) and extract the values of the second row.

In [26]:
a2= np.random.random((3,3))
a2[1]

array([0.11576312, 0.36035271, 0.55358708])

#### 9. Create a 5x5 matrix with values 1 to 25 and extract the element in the third row and fourth column.


In [71]:
a3 = np.arange(1,26).reshape(5,5)

print(a3)
print(" ")
print(a3[2][3])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
 
14


#### 10. Find the shape, size, and data type of a given Numpy array.


In [38]:
a3.shape,a3.size,a3.dtype

((5, 5), 25, dtype('int32'))

#### 11. Flatten a given 2D Numpy array.

In [46]:
a1= np.array([[1,2, 3],
           [4,5,6]])
a2=a1.flatten()
a2

array([1, 2, 3, 4, 5, 6])

#### 12. Concatenate two Numpy arrays along the second axis.

In [49]:
a1= np.array([[1,2, 3],
           [4,5,6]])
a2= np.array([[7,8,9],
              [10,11,12]])
np.concatenate((a1,a2), axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

#### 13. Split a given Numpy array into 3 equal-sized sub-arrays.

In [52]:
a3 = np.arange(1,10).reshape(3,3)
np.split(a3,3,axis=0)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

In [53]:
a3 = np.arange(1,10).reshape(3,3)
np.split(a3,3,axis=1)

[array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]]),
 array([[3],
        [6],
        [9]])]

#### 14. Create a Numpy array with 10 random integers between 1 and 100, and find the maximum and minimum values.

In [68]:
R= np.random.randint(1,101,size=10)
print(R)

print("\nMaximum value is: ",np.max(R))
print("Minimum value is: ",np.min(R))

[95 28 39  9 73 37 76 53 42 70]

Maximum value is:  95
Minimum value is:  9


#### 15. Create a Numpy array with random values and replace all values greater than 0.5 with 1.

In [74]:
S= np.random.rand(10)
print("The array is : ",S)
S[S>0.5]=1
print ("\nArray after replacing: ",S)

The array is :  [0.52507873 0.5296313  0.77948918 0.28090255 0.08529312 0.04449677
 0.29076806 0.57420872 0.33716918 0.25473895]

Array after replacing:  [1.         1.         1.         0.28090255 0.08529312 0.04449677
 0.29076806 1.         0.33716918 0.25473895]


#### 16. Multiply two given Numpy arrays element-wise.

In [76]:
a1= np.array([[1,2, 3],
           [4,5,6]])
a2= np.array([[7,8,9],
              [10,11,12]])
np.multiply(a1,a2)

array([[ 7, 16, 27],
       [40, 55, 72]])

#### 17. Compute the dot product of two given Numpy arrays.

In [81]:
a1= np.array([[1,2,3],
           [4,5,6]])
a2= np.array([[7,8],
              [8,9],
              [10,11]])
np.dot(a1,a2)

array([[ 53,  59],
       [128, 143]])

#### 18. Add a scalar value to a given Numpy array.

In [82]:
a1= np.array([[1,2,3],
           [4,5,6]])
a2=a1+5
a2

array([[ 6,  7,  8],
       [ 9, 10, 11]])

#### 19. Subtract one Numpy array from another.

In [85]:
a1= np.array([[7,18,9],
              [10,15,19]])
a2= np.array([[3,2, 3],
           [4,5,6]])
np.subtract(a1,a2)

array([[ 4, 16,  6],
       [ 6, 10, 13]])

#### 20. Find the mean, median, and standard deviation of a given Numpy array.

In [97]:
a1= np.array([[7,18,9],
              [10,15,19]])
print("Mean:" ,np.mean(a1))
print("Median:" ,np.median(a1))
print("Standard Deviation:" ,np.round(np.std(a1),decimals=2))

Mean: 13.0
Median: 12.5
Standard Deviation: 4.58


#### 21. Sort a given Numpy array along the first axis.


In [98]:
a1= np.array([[7,18,9],
              [10,15,19]])
np.sort(a1, axis=0)

array([[ 7, 15,  9],
       [10, 18, 19]])

#### 22. Find the unique elements of a given Numpy array.

In [100]:
a3= np.array([[ 2,  2,  3,  3,  8,  8],
       [ 4,  5,  6, 6, 11, 12]])
np.unique(a3)

array([ 2,  3,  4,  5,  6,  8, 11, 12])

#### 23. Check if a given Numpy array contains any NaN values.

In [101]:
arr = np.array([1, 2, np.nan, 4, 5])

has_nan = np.any(np.isnan(arr))

if has_nan:
    print("The array contains NaN values.")
else:
    print("The array does not contain NaN values.")

The array contains NaN values.


In [102]:
arr = np.array([1, 2, 3, 4, 5])

has_nan = np.any(np.isnan(arr))

if has_nan:
    print("The array contains NaN values.")
else:
    print("The array does not contain NaN values.")

The array does not contain NaN values.


#### 24. Create a 5x5 matrix and pad it with zeros along the border.

In [103]:
matrix = np.random.randint(1, 10, size=(5, 5))
print("Original matrix:")
print(matrix)

padded_matrix = np.pad(matrix, pad_width=1, mode='constant', constant_values=0)

print("\nPadded matrix with zeros along the border:")
print(padded_matrix)


Original matrix:
[[6 1 1 8 1]
 [8 4 1 6 8]
 [5 1 8 9 4]
 [7 7 2 8 6]
 [9 4 3 5 3]]

Padded matrix with zeros along the border:
[[0 0 0 0 0 0 0]
 [0 6 1 1 8 1 0]
 [0 8 4 1 6 8 0]
 [0 5 1 8 9 4 0]
 [0 7 7 2 8 6 0]
 [0 9 4 3 5 3 0]
 [0 0 0 0 0 0 0]]


#### 25. Transpose a given Numpy array.

In [104]:
a1= np.array([[7,18,9],
              [10,15,19]])
a2=np.transpose(a1)
a2

array([[ 7, 10],
       [18, 15],
       [ 9, 19]])

#### 26. Reverse the rows of a given 2D Numpy array.

In [109]:
a1= np.array([[7,18,9],
              [10,15,19]])
print(a1)
reversed_arr = a1[ : : -1]
print("\nReversed array: ",reversed_arr)

[[ 7 18  9]
 [10 15 19]]

Reversed array:  [[10 15 19]
 [ 7 18  9]]


#### 27. Compute the cumulative sum of a given Numpy array.

In [115]:
a1 = np.array([[7, 18, 9],
               [10, 15, 19]])

cumulative_sum_all = np.cumsum(a1)

print("Cumulative sum of all elements:")
print(cumulative_sum_all)

# cumulative sum along rows (axis=1)
cumulative_sum_rows = np.cumsum(a1, axis=1)

print("\nCumulative sum along rows (axis=1):")
print(cumulative_sum_rows)

# cumulative sum along columns (axis=0)
cumulative_sum_columns = np.cumsum(a1, axis=0)

print("\nCumulative sum along columns (axis=0):")
print(cumulative_sum_columns)


Cumulative sum of all elements:
[ 7 25 34 44 59 78]

Cumulative sum along rows (axis=1):
[[ 7 25 34]
 [10 25 44]]

Cumulative sum along columns (axis=0):
[[ 7 18  9]
 [17 33 28]]


#### 28. Normalize a given Numpy array.

In [116]:
a1 = np.array([[7, 18, 9],
               [10, 15, 19]])

# Min-Max normalization
normalized_a1 = (a1 - np.min(a1)) / (np.max(a1) - np.min(a1))

print("Original array:")
print(a1)

print("\nNormalized array (Min-Max normalization):")
print(normalized_a1)


Original array:
[[ 7 18  9]
 [10 15 19]]

Normalized array (Min-Max normalization):
[[0.         0.91666667 0.16666667]
 [0.25       0.66666667 1.        ]]


#### 29.  Reshape a given Numpy array to have 1 row and multiple columns.

In [117]:
a1 = np.array([[1, 2, 3],
               [4, 5, 6]])
print("Original matrix: ", a1)
reshaped_a1 = a1.reshape(1, -1)
print("\nReshaped Matrix: ",reshaped_a1)

Original matrix:  [[1 2 3]
 [4 5 6]]

Reshaped Matrix:  [[1 2 3 4 5 6]]
